CREATE TABLE IF NOT EXISTS `dag_step` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `dag_id` INT UNSIGNED NOT NULL,
    `name` TEXT NOT NULL,
    `content_path` TEXT NOT NULL,
    `command` TEXT NOT NULL,
    `status` TEXT NOT NULL,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FOREIGN KEY (`dag_id`) REFERENCES `dag` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
