development:
  dialect: mysql
  dir: db/migrations
  datasource: dtv-discord:dtv-discord@tcp(db)/dtv?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

production:
  dialect: mysql
  dir: db/migrations
  datasource: dtv-discord:dtv-discord@tcp(db)/dtv?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
