// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: discord_server.sql

package db

import (
	"context"
)

const insertServerId = `-- name: InsertServerId :exec
INSERT INTO discord_server (server_id)
VALUES (?)
ON DUPLICATE KEY UPDATE
    server_id = VALUES(server_id)
`

func (q *Queries) InsertServerId(ctx context.Context, serverID string) error {
	_, err := q.db.ExecContext(ctx, insertServerId, serverID)
	return err
}
