// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"encoding/json"
	"time"
)

type Program struct {
	ID          int64           `json:"id"`
	Json        json.RawMessage `json:"-"`
	EventID     int32           `json:"eventId"`
	ServiceID   int32           `json:"serviceId"`
	NetworkID   int32           `json:"networkId"`
	StartAt     int64           `json:"startAt"`
	Duration    int32           `json:"duration"`
	IsFree      bool            `json:"isFree"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	CreatedAt   time.Time       `json:"-"`
	UpdatedAt   time.Time       `json:"-"`
}

type ProgramMessage struct {
	ID        int32     `json:"id"`
	MessageID string    `json:"messageID"`
	ProgramID int64     `json:"programID"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
