// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: program.sql

package db

import (
	"context"
)

const getProgram = `-- name: GetProgram :one
SELECT id, json, event_id, service_id, network_id, start_at, duration, is_free, name, description, genre, created_at, updated_at FROM ` + "`" + `program` + "`" + ` WHERE ` + "`" + `id` + "`" + ` = ?
`

func (q *Queries) GetProgram(ctx context.Context, id int64) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgram, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Json,
		&i.EventID,
		&i.ServiceID,
		&i.NetworkID,
		&i.StartAt,
		&i.Duration,
		&i.IsFree,
		&i.Name,
		&i.Description,
		&i.Genre,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProgramWithMessageAndServiceName = `-- name: ListProgramWithMessageAndServiceName :many
SELECT
    ` + "`" + `program` + "`" + `.` + "`" + `id` + "`" + ` AS ` + "`" + `program_id` + "`" + `,
    ` + "`" + `program` + "`" + `.` + "`" + `json` + "`" + `,
    ` + "`" + `program` + "`" + `.` + "`" + `event_id` + "`" + `,
    ` + "`" + `program` + "`" + `.` + "`" + `service_id` + "`" + `,
    ` + "`" + `program` + "`" + `.` + "`" + `network_id` + "`" + `,
    ` + "`" + `program` + "`" + `.` + "`" + `start_at` + "`" + `,
    ` + "`" + `program` + "`" + `.` + "`" + `duration` + "`" + `,
    ` + "`" + `program` + "`" + `.` + "`" + `is_free` + "`" + `,
    ` + "`" + `program` + "`" + `.` + "`" + `name` + "`" + `,
    ` + "`" + `program` + "`" + `.` + "`" + `description` + "`" + `,
    ` + "`" + `program` + "`" + `.` + "`" + `genre` + "`" + `,
    ` + "`" + `program_message` + "`" + `.` + "`" + `channel_id` + "`" + `,
    ` + "`" + `program_message` + "`" + `.` + "`" + `message_id` + "`" + `,
    ` + "`" + `service` + "`" + `.` + "`" + `name` + "`" + ` AS ` + "`" + `service_name` + "`" + `
FROM ` + "`" + `program` + "`" + `
JOIN ` + "`" + `program_message` + "`" + ` ON ` + "`" + `program_message` + "`" + `.` + "`" + `program_id` + "`" + ` = ` + "`" + `program` + "`" + `.` + "`" + `id` + "`" + `
JOIN ` + "`" + `service` + "`" + ` ON ` + "`" + `program` + "`" + `.` + "`" + `service_id` + "`" + ` = ` + "`" + `service` + "`" + `.` + "`" + `service_id` + "`" + ` AND ` + "`" + `program` + "`" + `.` + "`" + `network_id` + "`" + ` = ` + "`" + `service` + "`" + `.` + "`" + `network_id` + "`" + `
`

type ListProgramWithMessageAndServiceNameRow struct {
	ProgramID   int64  `json:"programID"`
	Json        string `json:"json"`
	EventID     int32  `json:"eventID"`
	ServiceID   int32  `json:"serviceID"`
	NetworkID   int32  `json:"networkID"`
	StartAt     int64  `json:"startAt"`
	Duration    int32  `json:"duration"`
	IsFree      bool   `json:"isFree"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Genre       string `json:"genre"`
	ChannelID   string `json:"channelID"`
	MessageID   string `json:"messageID"`
	ServiceName string `json:"serviceName"`
}

func (q *Queries) ListProgramWithMessageAndServiceName(ctx context.Context) ([]ListProgramWithMessageAndServiceNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listProgramWithMessageAndServiceName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramWithMessageAndServiceNameRow
	for rows.Next() {
		var i ListProgramWithMessageAndServiceNameRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.Json,
			&i.EventID,
			&i.ServiceID,
			&i.NetworkID,
			&i.StartAt,
			&i.Duration,
			&i.IsFree,
			&i.Name,
			&i.Description,
			&i.Genre,
			&i.ChannelID,
			&i.MessageID,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProgram = `-- name: createProgram :exec
INSERT INTO ` + "`" + `program` + "`" + ` (
    ` + "`" + `id` + "`" + `,
    ` + "`" + `json` + "`" + `,
    ` + "`" + `event_id` + "`" + `,
    ` + "`" + `service_id` + "`" + `,
    ` + "`" + `network_id` + "`" + `,
    ` + "`" + `start_at` + "`" + `,
    ` + "`" + `duration` + "`" + `,
    ` + "`" + `is_free` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `description` + "`" + `,
    ` + "`" + `genre` + "`" + `
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type createProgramParams struct {
	ID          int64  `json:"id"`
	Json        string `json:"json"`
	EventID     int32  `json:"eventID"`
	ServiceID   int32  `json:"serviceID"`
	NetworkID   int32  `json:"networkID"`
	StartAt     int64  `json:"startAt"`
	Duration    int32  `json:"duration"`
	IsFree      bool   `json:"isFree"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Genre       string `json:"genre"`
}

func (q *Queries) createProgram(ctx context.Context, arg createProgramParams) error {
	_, err := q.db.ExecContext(ctx, createProgram,
		arg.ID,
		arg.Json,
		arg.EventID,
		arg.ServiceID,
		arg.NetworkID,
		arg.StartAt,
		arg.Duration,
		arg.IsFree,
		arg.Name,
		arg.Description,
		arg.Genre,
	)
	return err
}

const updateProgram = `-- name: updateProgram :exec
UPDATE ` + "`" + `program` + "`" + ` SET
    ` + "`" + `json` + "`" + ` = ?,
    ` + "`" + `event_id` + "`" + ` = ?,
    ` + "`" + `service_id` + "`" + ` = ?,
    ` + "`" + `network_id` + "`" + ` = ?,
    ` + "`" + `start_at` + "`" + ` = ?,
    ` + "`" + `duration` + "`" + ` = ?,
    ` + "`" + `is_free` + "`" + ` = ?,
    ` + "`" + `name` + "`" + ` = ?,
    ` + "`" + `description` + "`" + ` = ?
WHERE id = ?
`

type updateProgramParams struct {
	Json        string `json:"json"`
	EventID     int32  `json:"eventID"`
	ServiceID   int32  `json:"serviceID"`
	NetworkID   int32  `json:"networkID"`
	StartAt     int64  `json:"startAt"`
	Duration    int32  `json:"duration"`
	IsFree      bool   `json:"isFree"`
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          int64  `json:"id"`
}

func (q *Queries) updateProgram(ctx context.Context, arg updateProgramParams) error {
	_, err := q.db.ExecContext(ctx, updateProgram,
		arg.Json,
		arg.EventID,
		arg.ServiceID,
		arg.NetworkID,
		arg.StartAt,
		arg.Duration,
		arg.IsFree,
		arg.Name,
		arg.Description,
		arg.ID,
	)
	return err
}
