# ref: https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54

name: Docker

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache: true
      - name: Run goreleaser build
        if: github.event_name == 'pull_request'
        uses: goreleaser/goreleaser-action@v3
        with:
          args: build --clean --snapshot --single-target
      - name: Run goreleaser release
        if: github.event_name != 'pull_request'
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
